/* eslint-disable */
// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export function routes(searchParams) {
  const query = searchParams ? '?' + new URLSearchParams(searchParams).toString() : '';
  return {
    index: `/${query}` ,
    _404: (_404) => ({index: `/${_404}${query}`}),
    about: {index: `/about${query}`},
    home: {
      chat: {index: `/home/chat${query}`},
      editProfile: {index: `/home/edit-profile${query}`},
      settings: {
        theme: {index: `/home/settings/theme${query}`},
        contact: {index: `/home/settings/contact${query}`},
        profile: {index: `/home/settings/profile${query}`},
        complaint: {index: `/home/settings/complaint${query}`},
        complaints: {index: `/home/settings/complaints${query}`},
      },
    },
    auth: {
      signIn: {
        index: `/auth/sign-in${query}`,
        forgotPassword: {index: `/auth/sign-in/forgot-password${query}`},
      },
      signUp: {
        index: `/auth/sign-up${query}`,
        success: {index: `/auth/sign-up/success${query}`},
      },
    },
  };
}