// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export declare function routes(searchParams?: Record<string, string>): {
	index: string;
	_404: (_404: string | number) => { index: string };
	about: { index: string };
	home: {
		chat: {
			index: string;
			chatId: (chatId: string | number) => { index: string };
		};
		editProfile: { index: string };
		settings: {
			theme: { index: string };
			contact: { index: string };
			profile: { index: string };
			complaint: { index: string };
		};
	};
	auth: {
		signIn: {
			index: string;
			forgotPassword: { index: string };
		};
		signUp: {
			index: string;
			success: { index: string };
		};
	};
};
