// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export declare function routes(searchParams?: Record<string, string>): {
	index: string;
	_404: (_404: string | number) => { index: string };
	chat: { index: string };
	about: { index: string };
	auth: {
		signIn: { index: string };
		signUp: {
			index: string;
			success: { index: string };
		};
	};
};
