/* eslint-disable */
// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export function routes(searchParams) {
  const query = searchParams ? '?' + new URLSearchParams(searchParams).toString() : '';
  return {
    index: `/${query}` ,
    _404: (_404) => ({index: `/${_404}${query}`}),
    about: {index: `/about${query}`},
    auth: {
      signIn: {index: `/auth/sign-in${query}`},
      signUp: {
        index: `/auth/sign-up${query}`,
        success: {index: `/auth/sign-up/success${query}`},
      },
    },
  };
}